version: "3.9"
services:
  benchmark-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      # - .:/app
      - ${DB_PATH}:/app/instance
    environment:
      - FLASK_ENV=development
      - DB_PATH=${DB_PATH}
    restart: unless-stopped
