version: "3.9"
services:
  benchmark-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /my/host/path/to/db:/app/instance    # Datenbank-Ordner gemappt
    environment:
      - FLASK_ENV=development
